"""DodanieModeluGryKomputerowe

Revision ID: 9c1240c5f4cb
Revises: 
Create Date: 2025-12-01 19:16:24.337146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1240c5f4cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gry_komputerowe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa_gry', sa.String(length=255), nullable=False),
    sa.Column('gatunek', sa.String(length=100), nullable=False),
    sa.Column('czas_przejscia_h', sa.Integer(), nullable=False),
    sa.Column('czy_ukonczona', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa_gry')
    )
    op.create_index(op.f('ix_gry_komputerowe_id'), 'gry_komputerowe', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gry_komputerowe_id'), table_name='gry_komputerowe')
    op.drop_table('gry_komputerowe')
    # ### end Alembic commands ###
